version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db/:/var/lib/postgresql/data
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: aristotle_metadata_registry:dev
    command: sh ./sh/entrypoint/web.sh
    environment:
      - DATABASE_URL=postgresql://postgres:@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=settings
      - PYTHONPATH=.
      - DJANGO_DEBUG=True
    ports:
      - "8080:8000"
    volumes:
        - ../:/usr/src/app
        - ./data:/data
    depends_on:
      - db
