name: Linting
on: pull_request

jobs:
  python_lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v1'
      - name: Setup python
        uses: 'actions/setup-python@v1'
        with:
          python-version: 3.6
      - name: Install flake8
        run: pip install flake8
      - name: Lint
        run: flake8
  python_typing:
    name: Python type checking
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v1'
      - name: Setup python
        uses: 'actions/setup-python@v1'
        with:
          python-version: 3.6
      - name: Install mypy
        run: pip install mypy
      - name: Type checking
        shell: bash
        run: |
          mypy $(find ./python/ -maxdepth 3 -name '__init__.py' -printf '%h\n')
  js_lint:
    name: Javascript Lint
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v1'
      - name: Setup node
        uses: 'actions/setup-node@v1'
        with:
          node-version: 10
      - name: Install dependancies
        run: |
          cd assets
          npm install
      - name: Lint
        run: |
          cd assets
          npm run lint
